version: "1.0"
services:
  telegram-bot:
    type: web
    build:
      type: dockerfile
      dockerfile: Dockerfile
    ports:
      - 8080
    environment:
      - BOT_TOKEN=$BOT_TOKEN
    resources:
      memory: 512MB
      cpu: 0.5